In [74]:
from string import ascii_uppercase, ascii_lowercase
from random import choice
import numpy as np
import math

In [75]:
#functions for generating a set o K words that whose sum of letters adds up to a given sum

In [76]:
def sum_sub_vect(vect, n, sum):
     
    curr_sum = vect[0]
    start = 0
 
    i = 1
    while i <= n:
        
        while curr_sum  < sum:
            curr_sum = curr_sum + vect[i]
            i += 1
    
        if curr_sum == sum:
            return vect[start:i]
        else:
            curr_sum = curr_sum - vect[start]
            start += 1
         
    if i  == n & curr_sum != sum:
        return("No subarray found, increase sample size N")
    

In [77]:
#weights = a vector of the number of letters in each word to sample
def best_set(weights, n, sum):

    for iter in range(10):
        vect=np.random.choice(weights, n)
        out_set= len(set(sum_sub_vect(vect=vect,n=n, sum=sum)))
    
        if out_set == len(weights):
            break
    
    return sum_sub_vect(vect=vect,n=n, sum=sum)
        

In [78]:
# n - is size of ranom vector of weghts to select from, Integer
# N = total cells in grid - Integer
# x = word density of selected words enter as proportion

def get_words(word_dict, weights, n, N, x):
    sum = math.ceil(N*x)
    out_values=best_set(weights=weights,n=n,sum=sum)
    words_out = []
    for i in range(len(out_values)):
        words_out.append(list(word_dict.keys())[list(word_dict.values()).index(out_values[i])])
    return words_out


In [79]:
#tests

In [80]:
test = np.random.choice([4,5,7,5,3],50, p=[0.1, 0.2, 0.3, 0.2, 0.2])
test

array([5, 4, 7, 3, 7, 7, 3, 7, 5, 5, 4, 5, 5, 3, 3, 5, 3, 7, 3, 5, 3, 7, 7,
       5, 5, 4, 7, 5, 4, 5, 3, 7, 7, 3, 5, 5, 5, 5, 4, 5, 4, 5, 3, 3, 5, 5,
       5, 7, 7, 7])

In [81]:
sum_sub_vect(test,50, 30)

array([5, 5, 4, 5, 5, 3, 3])

In [82]:
out_values=best_set(weights=[5,3,7], n=50, sum=30)

In [83]:
out_values

array([5, 7, 5, 5, 5, 3])

In [84]:
words_for_grid = get_words(word_dict = {'HOUSE':5,'DOG':3, 'KITCHEN':7}, weights=[5,3,7], n=50, N=144, x=0.25)

In [85]:
words_for_grid

['HOUSE', 'DOG', 'DOG', 'KITCHEN', 'HOUSE', 'KITCHEN', 'DOG', 'DOG']

In [86]:
0.25*144

36.0

In [90]:
letters=0
for letter in ''.join(words_for_grid):
    letters +=1
letters


36